### ISSUE TITLE
Add Bitshares Graphic (~$50)

### ISSUE THREAD

**Issue by super3** [super3/invictus.io#11]
Under "Coins, Software, and DACs" Bitshares needs to have a good looking graphic. This can consist of the current logo, or something else.

**Comment by zwaffell** [comment]
What is the current logo ? Is it this one ?
![bitshares](https://f.cloud.github.com/assets/6280959/1821799/9bd3fe5e-7141-11e3-800e-451850911119.png)

**Comment by super3** [comment]
Yes. I believe so. I guess ask Bytemaster for the source files for that logo.
