### ISSUE TITLE
Simple Price Chart Widget (~$800 bounty)

### ISSUE THREAD

**Issue by super3** [super3/invictus.io#3]
**Core Spec:**
Stock Charts and price quotes may be the only dynamic content.

**Needed:**
A clean looking javascript widget that gives live information on current Protoshare prices. Should display all current exchanges that trade Protoshares, and include basic information such as latest price, high, low, and volume.

**Todo:**
- [x] Write Full Tech Spec

**Comment by pooleja** [comment]
I might be interested in working on this.  

Do we want to support all the exchanges listed on the Protoshares website?
- Bter Exchange
- Cryptsy Exchange
- Btc38 Exchange
- Peatio Exchange

Would all the information be shown from each exchange, or would the user select a specific exchange to display?

What logic components would the chart need?  Would it be a simple line graph like http://coinmarketcap.com or more detailed like http://bitcoinity.org/markets?

**Comment by super3** [comment]
Go for it. Yes, those 4 exchanges should do for now. 
A simple graph and market stats like http://coinmarkcap.com will do.

If you could make it more detailed like Bitcoinity that would be preferred though. What can you get done in the next 1-2 days?

**Comment by pooleja** [comment]
OK, cool.  I'm looking at it now.  The second two exchanges are a little harder to work with since they are Chinese, but I will see what I can get.

Also, I'm not quite sure where to get the historical data for the chart, but I will investigate that further.  I will send you a pull request when I get a little further (probably tonight).

**Comment by super3** [comment]
Just try your best and see what you can get in there tonight. We can always
improve it if its not enough.

Thanks!

**Comment by pooleja** [comment]
I ended up creating an entirely different page to display the price info and chart (and created a pull request).  Let me know if you would like me to put it directly into the ProtoShares page or somewhere else.

**Comment by super3** [comment]
Yes, if you could put pull req it into the protoshares page that would make my life much easier. Thanks!

**Comment by pooleja** [comment]
Updated the pull request so it shows the widget on the side of the ProtoShares page.

**Comment by super3** [comment]
Mostly Fixed as of 5414165547a71c9e6b295d653bfa605e798bb22f

**Comment by pooleja** [comment]
Sent a pull request to add the USD value of PTS to the stock widget.

**Comment by super3** [comment]
Done.

**Comment by super3** [comment]
Can you adjust the scale? Looks like PTS has flatlined.
