### ISSUE TITLE
New Angelshares Logo (~$200 bounty)

### ISSUE THREAD

**Issue by super3** [super3/invictus.io#4]
The full details for Angelshares is [listed here](http://invictus-innovations.com/angelshares). Please also see [http://invictus.io/](http://invictus.io/) for the placeholder spot next to Protoshares for color ideas. 

**Design Ideas:**
Gold, wings, coin. Just has to look professional in the end. 

**Current Logo(ick):**
![Imgur](http://i.imgur.com/VlDjA3Q.png)

**Comment by c055** [comment]
![ags_v2](https://f.cloud.github.com/assets/6280810/1819379/cd459de8-7089-11e3-8df5-c2f575c80356.png)

**Comment by c055** [comment]
![ags_v4](https://f.cloud.github.com/assets/6280810/1819399/a1666e84-708c-11e3-87c8-d38d69eff113.png)
![ags_v3](https://f.cloud.github.com/assets/6280810/1819400/a18ae41c-708c-11e3-963e-72fab7bf5d65.png)

**Comment by super3** [comment]
Ok. Really liking the second one. Can you mix the two?

**Comment by c055** [comment]
Hi super3 which version i should mixing !? 1/2 !? right?

**Comment by zwaffell** [comment]
![angelshares_v0 1](https://f.cloud.github.com/assets/6280959/1819440/8ca830c6-7092-11e3-8708-6933b518b88a.png)

**Comment by c055** [comment]
I just referred zwaffelcoin to this bounty :)

**Comment by zwaffell** [comment]
Cheers ! :+1:

**Comment by super3** [comment]
Making up the rules as I go.

@cassiopaia for referring get 10% of the sub-bounty.

@zwaffell you are the current winning logo. Will add it to the design. Note
that anyone can unseat you before submission.

**Comment by zwaffell** [comment]
I actually like the idea of wings in cassiopaia's logo. Maybe it's an idea to simplify and flatten it like this with the point and one without. What do you guys think, Halo or Wings ?

![angelshares_v0 2](https://f.cloud.github.com/assets/6280959/1820296/256d07bc-70e0-11e3-976c-d907d828e318.png)

![angelshares_v0 3](https://f.cloud.github.com/assets/6280959/1820298/3b91c514-70e0-11e3-91e1-2be63a22bf50.png)

**Comment by super3** [comment]
I still like this one so far.
![angelshares_v0 1](https://f.cloud.github.com/assets/6280959/1819440/8ca830c6-7092-11e3-8708-6933b518b88a.png)

Your new design looks good, but I don't think people would understand what it stands for. Could you label your designs with numbers or letters so we can refer to them easier?

**Comment by super3** [comment]
I have what I need for the Angelshares logo. You can continue to submit and contribute.

**Comment by zwaffell** [comment]
No offense but how am I supposed to interpret "I have what I need" ?

**Comment by super3** [comment]
I had a blank space for the angelshares logo, now I actually have something
to use. See the Invictus.io site.
