### ISSUE TITLE
Dead link to mining guide

### ISSUE THREAD

**Issue by Troglodactyl** [super3/invictus.io#65]
In bitshares-pts.php, the link to mining.html is dead.

**Comment by super3** [comment]
Pull req?

**Comment by Troglodactyl** [comment]
https://github.com/super3/invictus.io/pull/68

Just removed the reference for now.  Not sure if the mining guide was never written or written and then deleted for some reason.

**Comment by super3** [comment]
It was a copy paste from the Protoshares website.
